### ISSUE TITLE
Mask error

### ISSUE THREAD

**Issue by storeman** [mootools/mootools-more#1044]
In Mask.js is an error on the inject function, if the options.inject.where argument is set, it still is ignored. This is fixed by changing the line:

```javascript
where = where || (this.options.inject ? this.options.inject.where : '') || (this.target == document.body ? 'inside' : 'after');
```
Added the parentheses, this fixed my problem. Unfortunatly I couldn't fork the file, so I do it this way.

**Comment by SergioCrisostomo** [comment]
fixed by https://github.com/mootools/mootools-more/pull/1175
