### ISSUE TITLE
Create independent locale builder

### ISSUE THREAD

**Issue by xorock** [mootools/mootools-more#1065]
When I create a new mootools extra build I do not need all locales. So I must uncheck all and select those I need. Maybe You could create two sections: one with all extra classes (Date, Uri, Fx etc) and below just for locales (with select all/none buttons). Alternatively, you can transfer locale files to some different section and create third build. What do You think?

**Comment by SergioCrisostomo** [comment]
This has been possible since we released the new website: http://mootools.net/more/builder

Thanks for bringing this up.
