### ISSUE TITLE
In iOS Mobile Safari with debug console bar on: window.getSize().y != window.innerHeight

### ISSUE THREAD

**Issue by RiZKiT** [mootools/mootools-more#1079]
Normally window.getSize().y seems to give the same results as window.innerHeight, in Firefox, IE, Chrome and Mobile Safari.

But if you activate the debug console in iOS Mobile Safari, the windows height is calculated wrong by 48 pixel (I expect it's the size of the debug console bar). And thats wrong, because the debug console is only visible at the top of the page.
Looks like a Mobile Safari Bug!?

It's easily reproducable, when you show both values in an alert().

**Comment by SergioCrisostomo** [comment]
I think this has been fixed in Safari by now.

Tested in Safari 9 and its gone. 
http://jsfiddle.net/jufb23Lu/

Cheers.
