### ISSUE TITLE
drag on ipad/iphone doesnt work

### ISSUE THREAD

**Issue by rstafstrom** [mootools/mootools-more#1087]
None of the drag demos work on the iphone or ipad running safari.  The object doesn't drag.

I haven't seen any doc saying they shouldn't work on a touchscreen???  DocType issue?

**Comment by SergioCrisostomo** [comment]
This is actually fixed since https://github.com/mootools/mootools-more/commit/d0045cf41dbca84e32e8068e7bc5a46846bbd251.
