### ISSUE TITLE
Drag.move disables input text edit mode.

### ISSUE THREAD

**Issue by swamyv** [mootools/mootools-more#1159]
Here is a simple script. I pasted it on jsfiddle and tried it. Drag works but can not enter value to input box.
Same code works fine on IE but issue is in FireFox and chrome. 

HTML:

```
<div id='popup' class='popwin'>
    <div id='header' class='header'> </div>
    <div id='prop_input' > < input id='input' value='enter value'> </input> </div>
</div>
```

CSS:
```
#popup {
  background-color: #fff;
  border: 1px solid #303030;
  float: left;
  top:500px;    
  width: 30%;
  height:100px;
}

#header {
  background-color: #4422ff;
  border: 1px solid #808080;
  float: left;
  width: 99%;
  height:20px;
  cursor:'move';
}
```

JS:

```
var popwin = $$('.popwin');
$$('.header').setStyle('cursor', 'move');
var dragme = function(event) {
    var draga = new Drag.Move(this, {
    });
    draga.start(event);
};
popwin.addEvent('mousedown', dragme);
```

Test case on  jsfiddle.net

http://jsfiddle.net/CvGcb/4/

**Comment by SergioCrisostomo** [comment]
Fixed in https://github.com/mootools/mootools-more/commit/fa1acb1a216b2595abe04bf132ba8f77a7d1ae91

**Comment by anitaassusanto** [comment]
<a href="http://www.pokeridnplay.net/">http://www.pokeridnplay.net/</a>
<a href="http://www.pokerandroid.co/">http://www.pokerandroid.co/</a>
<a href="http://www.idnpokerandroid.com/">http://www.idnpokerandroid.com/</a>
<a href="http://www.karturemipoker.com/">http://www.karturemipoker.com/</a>
<a href="http://www.remipoker88.com/">http://www.remipoker88.com/</a>
<a href="https://www.remi88.co/">http://www.remi88.co/</a>
<a href="http://www.remisong.com/">http://www.remisong.com/</a>
<a href="http://www.remileng.com/">http://www.remileng.com/</a>
<a href="http://www.poker-uangasli.com/">http://www.poker-uangasli.com/</a>
<a href="http://www.pokeruang-asli.com/">http://www.pokeruang-asli.com/</a>
<a href="http://www.idnsamgong.com/">http://www.idnsamgong.com/</a>
<a href="http://www.superten.org/">http://www.superten.org/</a>
<a href="http://www.samgong-online.co/">http://www.samgong-online.co/</a>
<a href="http://idnpokerandroid.com/">http://idnpokerandroid.com/</a>
<a href="https://www.daftargapleonline.net/">https://www.daftargapleonline.net/</a>
<a href="http://www.pokeridnplay.net/poker-idnplay/">poker idnplay</a>
<a href="http://www.pokeridnplay.net/login-poker-idnplay/">login poker idnplay</a>
<a href="http://www.pokeridnplay.net/idnplay-poker/">idnplay poker</a>
<a href="http://www.pokerandroid.co/idn-poker-android/">idn poker android</a>
<a href="http://www.karturemipoker.com/download-kartu-remi-poker/">download kartu remi poker</a>
<a href="http://www.karturemipoker.com/kartu-remi-poker/">kartu remi poker</a>
<a href="http://www.remipoker88.com/login-poker88/">login poker88</a>
<a href="http://www.remipoker88.com/freechip-poker-uang-asli-tanpa-deposit/">freechip poker tanpa deposit</a>
<a href="https://www.remi88.co/daftar-poker-online/">daftar poker online</a>
<a href="https://www.remi88.co/daftar-domino-qq-online/">daftar domino qq online</a>
<a href="https://www.remi88.co/daftar-domino-ceme-online/">daftar domino ceme online</a>
<a href="https://www.remi88.co/daftar-ceme-keliling-online/">daftar ceme keliling online</a>
<a href="https://www.remi88.co/daftar-capsa-susun-online/">daftar capsa susun online</a>
<a href="https://www.remi88.co/daftar-super10-online/">daftar super10 online</a>
<a href="http://www.poker-uangasli.com/poker-uang-asli/">poker uang asli</a>
<a href="http://www.pokeruang-asli.com/samgong-online/">samgong online</a>
<a href="http://www.idnsamgong.com/idn-samgong/">idn samgong</a>
<a href="http://www.superten.org/superten/">superten</a>
<a href="http://www.superten.org/daftar-superten/">daftar superten</a>
<a href="http://www.superten.org/agen-superten/">agen superten</a>
<a href="http://www.superten.org/login-superten/">login superten</a>
<a href="http://www.samgong-online.co/samgong-online/">samgong online</a>
<a href="http://www.idnpokerandroid.com/judi-ceme/">judi ceme</a>
<a href="http://www.idnpokerandroid.com/judi-kartu-online/">judi kartu online</a>
<a href="http://www.idnpokerandroid.com/judi-remi/">judi remi</a>
<a href="http://www.idnpokerandroid.com/judi-remi-online/">judi remi online</a>
<a href="http://www.idnpokerandroid.com/judi-domino/">judi domino</a>
