### ISSUE TITLE
More, Forms.Validator.Extras, validate-match matchName doesn't work if matchName contains spaces

### ISSUE THREAD

**Issue by kelexel** [mootools/mootools-more#1185]
As the title (tries) to suggest..
Set a Form.Validator.* on a form.
Set a field with a validate-match and matchName, put a space in matchName == bug
Bug demo:
http://tinker.io/5051c

Issue located at:
https://github.com/mootools/mootools-more/blob/master/Source/Forms/Form.Validator.Extras.js#L121

**Comment by SergioCrisostomo** [comment]
Related: #1213

**Comment by SergioCrisostomo** [comment]
merged/fixed in https://github.com/mootools/mootools-more/commit/8ce4ade40bbd1ed2937b6b8faae989e5e0eb5ec8
