### ISSUE TITLE
Undefined object when loading mootools-more using custom asset manager

### ISSUE THREAD

**Issue by Varyen** [mootools/mootools-more#1294]
I have custom JS asset manager in my project, it allowes me to use scripts dependencies, code minifying and other cool things.
Every script loades in `(function(){ ** code here** })()` including all libraries.

For example, I can't use Drag and Sortables objects, because you define them like that:
`var Drag = new Class({ ...`
`Drag` is local variable inside my loader

But I can use Keyboard object, because it's defined that way:
`var Keyboard = this.Keyboard = new Class(`

There're no problems with Core classes, because they're all binded to window.

Why you're not using `var ClassDef = this.ClassDef = new Class(` everywhere? It's more "bulletproof" solution.

**Comment by SergioCrisostomo** [comment]
fixed by 7d29eda3409417ad749621d7288f768de0e4abe3
