### ISSUE TITLE
Drag class is not exposed to the global correctly

### ISSUE THREAD

**Issue by IvanGuardado** [mootools/mootools-more#1310]
`Drag` class should be explicitly exposed to the global context using `this.Drag = ....` instead of using a var definition in the global scope.

The reason for this is that if you use a dependency manager like webpack the current method does not work well. However the other modules work without problem because they expose the classes into `this` or `window`.

https://github.com/mootools/mootools-more/blob/master/Source/Drag/Drag.js#L30

**Comment by SergioCrisostomo** [comment]
Thanks for pointing this.
Related: https://github.com/mootools/mootools-more/issues/1294

If you have time to send a pull request with that would nice. We will be reviewing this soon probably to export things as modules and this will have to be fixed by then.

**Comment by SergioCrisostomo** [comment]
fixed by 7d29eda3409417ad749621d7288f768de0e4abe3
