### ISSUE TITLE
More Builder creates broken JavaScript file

### ISSUE THREAD

**Issue by kije** [mootools/mootools-more#1319]
Hi
I just generated a fresh build of mootools-more with the More Builder on [mootools.net](http://mootools.net).

Build was: http://mootools.net/more/builder/21d92255a96fbd8a91d568b678e3e751

In the generated Javascrip-File is a semicolon (<code>;</code>) missing [on line 1467](https://gist.github.com/kije/0bb661c9994ca779b320#file-mootools-more-1-5-2-21d92255a96fbd8a91d568b678e3e751-js-L1467).

This happenes again, if I'm redownloading the build.

**Comment by cristscott89** [comment]
wonderful and extremely instructive article. I wonder why the other industry professionals do not comprehend this.   [skywestonline](https://skywestonlinnews.com/)
