### ISSUE TITLE
Form.Request throws error in more-1.5.2

### ISSUE THREAD

**Issue by odysseuscm** [mootools/mootools-more#1323]
When I build more with Form.Request I get an error upon load:
Uncaught TypeError: (intermediate value)(intermediate value)(...) is not a function
That's the anonymous function that implements QueryString parsing and cleanup (starts in line 1169 when I build only with Form.Request).

**Comment by odysseuscm** [comment]
It looks like a dependency bug in the builder. If I manually add Element.Event.Pseudos the error goes away.

**Comment by SergioCrisostomo** [comment]
@odysseuscm are you building More with Core or without? `compat` or `nocompat`?

**Comment by odysseuscm** [comment]
without Core and nocompat

**Comment by SergioCrisostomo** [comment]
@odysseuscm  I can't reproduce your error... 
Please check this jsFiddle with a comment and a link to a build of More I did just now.

**Comment by SergioCrisostomo** [comment]
And the jsFiddle :) -> http://jsfiddle.net/9ayufb1v/

**Comment by odysseuscm** [comment]
hm. if you add this script in your fiddle: http://kunden.cmcm.info/more/MooTools-More-1.5.2.js
do you get the error? I do.

**Comment by odysseuscm** [comment]
You used a complete build of more, didn't you? Try building one with only Form.Request.

**Comment by odysseuscm** [comment]
@SergioCrisostomo I'm curious, could you reproduce with a build of Form.Request only?

**Comment by SergioCrisostomo** [comment]
@odysseuscm i could reproduce it. Will investigate further, somehow the `;` in [this line](https://github.com/mootools/mootools-more/blob/master/Source/Types/String.QueryString.js#L86) is getting lost. Restoring it fixes the problem.

**Comment by SergioCrisostomo** [comment]
Fixed by #1319. We will update the website builder soon.
