### ISSUE TITLE
Rename Assets package to Asset

### ISSUE THREAD

**Issue by masted** [mootools/mootools-more#1334]
I'm writing tool for auto-building mootools dependencies by parsing code. And I have a problem with Object "Asset". It named in meta-data comments as "Assets". Why it was made like that? And can we rename Assets "package" to Asset?

**Comment by SergioCrisostomo** [comment]
If its a pattern that all other modules have then I guess we should change it. Lets see what others say.

**Comment by arian** [comment]
We could add `Asset.image, Asset.javascript, Asset.css` to the provides.

On the other hand, the requires / provides are supposed to match, we don't guarantee anywhere that this provided name actually matches some javascript variable name.

**Comment by SergioCrisostomo** [comment]
Good idea @arian.

@masted if you use `provides: [Asset.image, Asset.javascript, Asset.css]` in [this line](https://github.com/mootools/mootools-more/blob/1.5.2/Source/Utilities/Assets.js#L19) can your work with that in your tool?

**Comment by masted** [comment]
Yes. It would be enough

**Comment by anutron** [comment]
Note that provides (as we original envisioned it) does provide things that don't match necessarily. For example:

```
provides: [Class.Extras, Chain, Events, Options]
```

We also at some point (though I can't remember where) used this for deprecated names (i.e. some new feature replaced and old one and provided backwards compat for the old one, so it provided that thing too).

I think it's fine to provide numerous things. Here's another example where the filename is (by convention) `Class.Refactor` but the thing provided is a function, so it defines `Class.refactor`. So the provision is:

```
provides: [Class.refactor, Class.Refactor]
```

**Comment by SergioCrisostomo** [comment]
Fixed in https://github.com/mootools/mootools-more/pull/1335
