### ISSUE TITLE
Add element.makeRotatable method needed

### ISSUE THREAD

**Issue by newbie78** [mootools/mootools-more#1338]
I'm found this solution on the internet: http://jsfiddle.net/jessejamesrichard/j4uV2/10/
maybe it's worth it to implement to m-more like element.makeRotatable?
or something like that

thanx

**Comment by arian** [comment]
I think it's a bit too specific, and it's not a very common thing.

**Comment by newbie78** [comment]
I understand, but how a priming to start work on the feature?

**Comment by SergioCrisostomo** [comment]
I agree with @arian, would be a nice plugin to have in Forge though. Cool animation.
