### ISSUE TITLE
Unmet peer dependency: sinon@*

### ISSUE THREAD

**Issue by olvlvl** [mootools/mootools-more#1339]
Hi,

I tryed to run the tests for `mootools-more` but there was a dependency issue.

```
│   └── lodash@2.4.2
├── mootools-core@1.6.1-dev
├── requirejs@2.1.22
└── UNMET PEER DEPENDENCY sinon@*

npm WARN karma-sinon@1.0.4 requires a peer of sinon@* but none was installed.
```

I followed the steps defined in the README:

```
$ git clone https://github.com/mootools/mootools-more  # clone the MooTools repo
$ cd mootools-more                                     # get into the directory
$ npm install                                          # install de testing tools
$ npm install grunt-cli -g                             # install the Grunt command line interface
$ grunt default                                        # run the specs!
```

I fixed it by installing the package myself:

```
$ npm install sinon
```
##

**Comment by SergioCrisostomo** [comment]
@olvlvl  do the specs run? 
I can reproduce the warning but specs do run for me.

We need to update the Karma family dependencies to get these warnings fixed.

**Comment by olvlvl** [comment]
After installing `sinon` the specs run fine.

**Comment by SergioCrisostomo** [comment]
@olvlvl ok. Thanks for reporting this. If you have the fix ready welcome to send it. Otherwise we need to review this probably together with the Grunt re-organization Core received.

**Comment by arian** [comment]
npm install sinon --save-dev
