### ISSUE TITLE
How to make accordion closed on initial page

### ISSUE THREAD

**Issue by cici004** [mootools/mootools-more#1344]
I was trying to     set values in following way in my code in order to close all the accordion when the page loads initially but not working. I attached my code in the following link. Anybody can help? Thanks a lot!

```
          alwaysHide : true,
    display: -1,
    opacity: false,
    show: 0
```

https://gist.github.com/cici004/16ff35371b4d38ebb821b5ab2b35a7f2

**Comment by SergioCrisostomo** [comment]
Don't change the source code for the class, use the `options` argument instead. 
Another this is when you use `show: 0`, that overrides the `display: -1` option and shows the first element anyway.

So a solution would be to just ignore the `show` key and pass this object as argument to the class:

``` js
  var opts = {
    alwaysHide: true,
    display: -1
  }
  new Fx.Accordion($('accordion'), '#accordion h2', '#accordion .content', opts);
```

jsFiddle: http://jsfiddle.net/pLo5m95g/

If this did not solve your problem let me know.

**Comment by cici004** [comment]
Thanks for you reply Sergio. It is still not working :( I am trying to close the first part when the page was loaded

Here is the link for my code:

JS:   https://gist.github.com/cici004/4785c2fd71b1e686747662328fef25c0

HTML: https://gist.github.com/cici004/b7baf036ad4efc0076f67fc041716e0b

**Comment by cici004** [comment]
Thanks for you reply Sergio. It is still not working :( I am trying to
close the first part when the page was loaded

Here is the link for my code:

_JS:_   https://gist.github.com/cici004/4785c2fd71b1e686747662328fef25c0

_HTML_: https://gist.github.com/cici004/b7baf036ad4efc0076f67fc041716e0b

_Interface as below:_

[image: Inline image 1]

**Comment by cici004** [comment]
Thanks for you reply Sergio. It is still not working :( I am trying to
close the first part when the page was loaded

Here is the link for my code:

_JS:_   https://gist.github.com/cici004/4785c2fd71b1e686747662328fef25c0

_HTML_: https://gist.github.com/cici004/b7baf036ad4efc0076f67fc041716e0b

_Interface as below:_

[image: Inline image 1]

**Comment by cici004** [comment]
Hi mootools,

Check out the books I added on Goodreads.

http://www.goodreads.com/friend/i?i=LTM1MzQzOTIzNzQ6NDEz&e=reply@reply.github.com&n=mootools mootoolsmore&utm_medium=email&utm_source=invite

- Xi
(xihancooking@gmail.com)

Goodreads is a community for book lovers. It's a great way to get book recommendations from your friends and others. You can keep a list of books to read, join book clubs, and even take the never-ending book trivia quiz.

_____________________________


To opt-out of future invites to Goodreads please follow this link: http://www.goodreads.com/user/block_email?email_to_block=blRsZys5dFMwKzR4c05HeDdDNGpEWDRRY0tqd1hza1U4ckR1M2tCODkyL0QxZklDTmpTcHNsQmxNOTdDcHQ5NEkyQVRZTElLeFdPK1g3OHVzdkU5NW1TeU5rVXRWby9vUzRGMmZKUEJLeVBBYldJT2JRVzlKQVRBZUtzT05HZHQrRnpKeXBsV3pLZWlPWkV2V1hBVFduQ1hrNE9Eam5yL1BGQlJ2REkvNkk4PS0tYUcwNzlZNG9zaWtYQ3FxaHJNcmNrUT09--a164d850b2b403254209cb050726f2022aef0259&utm_content=A&utm_medium=email&utm_source=invite

This email was sent by request to reply@reply.github.com.

(c) 2017 Goodreads, Inc.
188 Spear Street, 3rd Floor, San Francisco, CA 94105
