### ISSUE TITLE
How to make accordion closed on initial page not working 

### ISSUE THREAD

**Issue by cici004** [mootools/mootools-more#1345]
I am trying to close the first part when the page was loaded even though I changed my code based on many suggestions it is still not working :(

Here is the link for my code:

JS:   https://gist.github.com/cici004/4785c2fd71b1e686747662328fef25c0

HTML: https://gist.github.com/cici004/b7baf036ad4efc0076f67fc041716e0b

**Comment by SergioCrisostomo** [comment]
@cici004 can you make a jsFiddle reproducing the problem please? I think this would fit best in Stackoverflow ( I am happy to help you there ).

**Comment by DimitarChristoff** [comment]
His html page template made me chuckle - `Last updated` in 2007, with a xhtml 1.0 strict doctype... Does this even work anymore?

Got to love that the State of California sticks to traditional values :roll_eyes:

**Comment by cici004** [comment]
Hi Sergio,

Here is the link for my code in jsFiddle.

https://jsfiddle.net/e5ddu8u8/

**Comment by SergioCrisostomo** [comment]
Closing, this was solved in PM some days ago.
The missing part was the `display: -1` setting in the configuration object.
