### ISSUE TITLE
:relay() doesn't listen to fireEvent

### ISSUE THREAD

**Issue by antpaw** [mootools/mootools-more#208]
`console.log('relay click');` never gets triggered if i rollover my green box. i think it's a bug. relay should be listening for elem.fireEvent();
here is a testcase, you obviously need a mootools-more version with relay support.

	<!DOCTYPE html>
	<html>
		<head>
			<meta charset="utf-8">
			<title>test</title>
		</head>
		<body>
			<div id="box" style="width: 200px; height:200px; background: green"></div>
			<a href="http://google.de" id="plus">+</span>
			<script src="http://ajax.googleapis.com/ajax/libs/mootools/1.3/mootools-yui-compressed.js"></script> 
			<script src="mootools-more.js"></script> 
			<script>
				$('box').addEvent('mouseenter', function(e){
					$('plus').fireEvent('click', [e]);
				});
				document.body.addEvent('click:relay(a)', function(e){
					console.log('relay click');
					e.preventDefault();
				});
				$$('a').addEvent('click', function(e){
					console.log('fixed click');
					e.preventDefault();
				});
			</script>
		</body>
	</html>

**Comment by SergioCrisostomo** [comment]
Closing. I'm cleaning around old issues. Let me know if it should be reopened.
